// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALJwZK3MruqeNVckiRRINIjejPLDQf7wk',
    appId: '1:493264433529:web:51609bd77219203a21bfa8',
    messagingSenderId: '493264433529',
    projectId: 'internship-management-sy-8ce13',
    authDomain: 'internship-management-sy-8ce13.firebaseapp.com',
    storageBucket: 'internship-management-sy-8ce13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkRIj3RUNOpl6Jp46bu-FbitY2nvPdIaI',
    appId: '1:493264433529:android:283aabab945bac3b21bfa8',
    messagingSenderId: '493264433529',
    projectId: 'internship-management-sy-8ce13',
    storageBucket: 'internship-management-sy-8ce13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEvW5Dg2mnmlLZ5oRbQAuWOiQ96TnAW-8',
    appId: '1:493264433529:ios:5c35a02a994e803d21bfa8',
    messagingSenderId: '493264433529',
    projectId: 'internship-management-sy-8ce13',
    storageBucket: 'internship-management-sy-8ce13.appspot.com',
    iosBundleId: 'com.example.ims',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEvW5Dg2mnmlLZ5oRbQAuWOiQ96TnAW-8',
    appId: '1:493264433529:ios:5c35a02a994e803d21bfa8',
    messagingSenderId: '493264433529',
    projectId: 'internship-management-sy-8ce13',
    storageBucket: 'internship-management-sy-8ce13.appspot.com',
    iosBundleId: 'com.example.ims',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALJwZK3MruqeNVckiRRINIjejPLDQf7wk',
    appId: '1:493264433529:web:3d1e857e0b809f0c21bfa8',
    messagingSenderId: '493264433529',
    projectId: 'internship-management-sy-8ce13',
    authDomain: 'internship-management-sy-8ce13.firebaseapp.com',
    storageBucket: 'internship-management-sy-8ce13.appspot.com',
  );
}
